ProgettoArduAlessio/ProgettoArduAlessio/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Base import views
from ProgettoArduAlessio import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('user_management/', include('user_management.urls')),
    path('user_profile/', include('user_profile.urls')),
    path('posts/', include('posts.urls')),
    path('integrated_messaging/', include('integrated_messaging.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProgettoArduAlessio/integrated_messaging/urls.py
from integrated_messaging import views
from django.urls import path

app_name = "integrated_messaging"

urlpatterns = [
    path("send/<int:pk_receiver>", views.send_message, name="message-send"),
    path("inbox/", views.inbox_home, name="inbox"),
    path("inbox/message/list/<int:pk_sender>", views.message_list, name="message-list"),
    path("inbox/send_message_inline_ajax", views.send_message_inline_ajax, name="send-message-inline-ajax"),
]

ProgettoArduAlessio/posts/urls.py
from django.urls import path
from posts import views

app_name = "posts"

urlpatterns = [
    path("offer/add/<int:pk>", views.OfferAdd.as_view(), name="offer-add"),
    path("offer/update/<int:pk>/<int:pk_offer>", views.offer_update, name="offer-update"),
    path("offer/delete/<int:pk>/<int:pk_offer>", views.offer_delete, name="offer-delete"),
    path("offer/update/visible/<int:pk>/<int:pk_offer>", views.offer_visible_update, name="offer-update-visible"),
    path("offer/update/photos/<int:pk>/<int:pk_offer>", views.OfferPhotosUpdate.as_view(), name="offer-update-photos"),
    path("offer/review/add/<int:pk>/<int:pk_offer>", views.offer_add_review, name="offer-add-review"),
    path("offer/review/<int:pk_offer>", views.offer_review_list, name="offer-review-list"),
    path("offer/detail/<int:pk>", views.OfferDetail.as_view(), name="offer-detail"),

    path("request/list/<int:pk>", views.request_list, name="request-list"),
    path("request/add/<int:pk>", views.RequestAdd.as_view(), name="request-add"),
    path("request/update/<int:pk>/<int:pk_request>", views.request_update, name="request-update"),
    path("request/delete/<int:pk>/<int:pk_request>", views.request_delete, name="request-delete"),
    path("request/detail/<int:pk>", views.RequestDetail.as_view(), name="request-detail"),
    path("request/add/offer/<int:pk_request>", views.offer_to_request, name="offer-to-request"),
    path("request/list/offers/<int:pk_request>", views.offers_for_request_list, name="offers-for-request-list"),

    path("offer/buy/<int:pk>/<int:pk_offer>", views.offer_buy, name="offer-buy"),
    path("offer/bought/list/<int:pk>", views.offers_bought_list, name="offers-bought-list"),

    path("offer/search", views.offer_search, name="offer-search"),

    path("seller/search", views.seller_search, name="seller-search"),

    path("orders/<int:pk>", views.orders, name="orders"),

]

ProgettoArduAlessio/integrated_messaging/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
from user_management.models import MyUser


class Message(models.Model):
    sender = models.ForeignKey(MyUser, on_delete=models.PROTECT, related_name="sender_messages")
    receiver = models.ForeignKey(MyUser, on_delete=models.PROTECT, related_name="receiver_messages")
    message_content = models.CharField(max_length=140)
    date = models.DateTimeField(auto_now=True)

ProgettoArduAlessio/integrated_messaging/forms.py
from django import forms

from integrated_messaging.models import Message


class MessageSendForm(forms.ModelForm):

    class Meta:
        model = Message
        fields = ("message_content", )

ProgettoArduAlessio/integrated_messaging/views.py
import json

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_protect

from integrated_messaging.forms import MessageSendForm
from integrated_messaging.models import Message
from user_management.models import MyUser


@login_required
def inbox_home(request):
    # selecting distinct senders
    list_of_dict_received = request.user.receiver_messages.values('sender').distinct()
    list_of_dict_sent = request.user.sender_messages.values('receiver').distinct()
    pk_senders = []
    pk_receivers = []
    for dic in list_of_dict_received:
        pk_senders.append(dic['sender'])
    for dic in list_of_dict_sent:
        pk_receivers.append(dic['receiver'])

    senders = MyUser.objects.filter(pk__in=pk_senders)
    receivers = MyUser.objects.filter(pk__in=pk_receivers)

    chat_users = senders.union(receivers)
    chat_user_count = chat_users.count()

    chat_user_dict = {}
    for chat_user in chat_users:
        messages1 = Message.objects.filter(sender=chat_user, receiver=request.user.pk)
        messages2 = Message.objects.filter(sender=request.user.pk, receiver=chat_user)
        chat_user_dict[chat_user] = messages1.union(messages2).order_by("-date").first()

    context = {
        "chat_users": chat_user_dict,
        "chat_user_count": chat_user_count,
    }
    return render(request, "integrated_messaging/inbox_home.html", context)


@login_required
def send_message(request, pk_receiver=""):
    receiver = MyUser.objects.get(pk=pk_receiver)
    if request.POST:
        form = MessageSendForm(request.POST)
        if form.is_valid():
            message = Message(sender=MyUser.objects.get(pk=request.user.pk), receiver=receiver,
                              message_content=form.cleaned_data['message_content'])
            message.save()
            return redirect(reverse_lazy("user_management:home", args=(receiver.pk,)))
    else:
        form = MessageSendForm()
        return render(request, "integrated_messaging/message/send.html", {
            "receiver": receiver,
            "form": form,
            "url": reverse_lazy("user_management:home", args=(receiver.pk,))
        })


@csrf_protect
def send_message_inline_ajax(request):

    if request.POST:
        message_content = request.POST.get('message_content')
        receiver = MyUser.objects.get(pk=request.POST.get('receiver_pk'))
        message = Message(sender=MyUser.objects.get(pk=request.user.pk), receiver=receiver,
                          message_content=message_content)
        message.save()

        #response_data = {'html_message': render(request, "integrated_messaging/message/my_message.html", {"message": message})}
        # return HttpResponse(
        #     json.dumps(response_data),
        #     content_type="application/json"
        # )
        return render(request, "integrated_messaging/message/my_message.html", {"message": message})
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"
        )


@login_required
def message_list(request, pk_sender=""):
    sender = MyUser.objects.get(pk=pk_sender)
    messages1 = Message.objects.filter(sender=sender, receiver=request.user.pk)
    messages2 = Message.objects.filter(sender=request.user.pk, receiver=sender)
    messages = messages1.union(messages2).order_by("date")

    return render(request, "integrated_messaging/message/list.html", {"messages": messages, "sender_view": sender})

ProgettoArduAlessio/integrated_messaging/templates/integrated_messaging/message/list.html
{% extends "base.html" %}

{% block centered_central_content %}
<div class="container-fluid mb-5">
    <div class="row">
    <div class="col"></div>
    <div class="col-10  p-3" style="background-color: #00ffc7">
        <div id="message-box">
        {% for message in messages %}
            <div class="row mt-3">
            {% if message.sender.pk == user.pk %}
               {% include "integrated_messaging/message/my_message.html" with message=message %}
            {% elif message.receiver.pk == user.pk %}
                {% include "integrated_messaging/message/other_user_message.html" with message=message %}
            {% endif %}
            </div>
        {% endfor %}

        </div>
        <div class="row d-flex justify-content-end mt-3" >
        <form id="post-form" method="POST" class="form-inline">
            <div class="d-flex mr-2">
                <input class=" form-control-plaintext bg-white " type="text" id="message-input" name="message-input" placeholder="Type a message">
            {% csrf_token %}
            <div id="results"></div>
            <button type="submit" class="btn btn-success ml-2">Send</button>
            </div>
        </form>
    </div>
    </div>

    <div class="col"></div>

    </div>

</div>
{% endblock %}
{% block javascript %}
    <script>
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');
        $(function () {
            $.ajaxSetup({
                headers: { "X-CSRFToken": csrftoken }
            });
        });
         function create_post() {
            console.log("create post is working!") // sanity check
            $.ajax({
                url : "{% url "integrated_messaging:send-message-inline-ajax" %}", // the endpoint
                type : "POST", // http method
                data : {
                    message_content : $('#message-input').val(),
                    receiver_pk : {{ sender_view.pk }},
                }, // data sent with the post request

                // handle a successful response
                success : function(result) {
                    $('#message-input').val(''); // remove the value from the input
                    console.log(result); // log the returned json to the console
                    $("#message-box").append(
                        "<div class=\"row mt-3\">" + result + "</div>"

                    );

                },

                // handle a non-successful response
                error : function(xhr,errmsg,err) {
                    $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                        " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
                    console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
                }
            });
        };


        $('#post-form').on('submit', function(event){
            event.preventDefault();
            console.log("form submitted!")  // sanity check
            create_post();
        });
     </script>
{% endblock %}

ProgettoArduAlessio/integrated_messaging/templates/integrated_messaging/message/my_message.html
<div class="col"></div>
<div class="col d-flex justify-content-end">

    <div class="bg-success rounded pl-4 pr-4">
        <div class="row">
            {{ message.message_content }}
        </div>
        <div class="row d-flex justify-content-end pt-3">
            <p style="text-align: right">{{ message.date }}</p>
        </div>
    </div>
</div>

ProgettoArduAlessio/integrated_messaging/templates/integrated_messaging/message/other_user_message.html
<div class="col d-flex justify-content-start">
    <div class="bg-white rounded pl-4 pr-4">
        <div class="row  border-bottom">
            {{ message.sender }}
        </div>
        <div class="row">
            {{ message.message_content }}
        </div>
        <div class="row d-flex justify-content-end pt-3">
            <p style="text-align: right">{{ message.date }}</p>
        </div>
    </div>

</div>
<div class="col"></div>

ProgettoArduAlessio/integrated_messaging/templates/integrated_messaging/message/send.html
{%  extends "base.html" %}

{% block title %}
Add Offer
{% endblock %}
{% block centered_central_content %}

    {% if request.resolver_match.kwargs.pk != user.pk %}

    {% include "form.html" with view_type="context_url" value="Send" %}

    {% else %}

    <div class="alert alert-warning" role="alert">
      You are not authorized
    </div>

    {% endif %}

{% endblock %}