ProgettoArduAlessio/ProgettoArduAlessio/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Base import views
from ProgettoArduAlessio import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('user_management/', include('user_management.urls')),
    path('user_profile/', include('user_profile.urls')),
    path('posts/', include('posts.urls')),
    path('integrated_messaging/', include('integrated_messaging.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProgettoArduAlessio/integrated_messaging/urls.py
from integrated_messaging import views
from django.urls import path

app_name = "integrated_messaging"

urlpatterns = [
    path("send/<int:pk_receiver>", views.send_message, name="message-send"),
    path("inbox/", views.inbox_home, name="inbox"),
    path("inbox/message/list/<int:pk_sender>", views.message_list, name="message-list"),
    path("inbox/send_message_inline_ajax", views.send_message_inline_ajax, name="send-message-inline-ajax"),
]

ProgettoArduAlessio/posts/urls.py
from django.urls import path
from posts import views

app_name = "posts"

urlpatterns = [
    path("offer/add/<int:pk>", views.OfferAdd.as_view(), name="offer-add"),
    path("offer/update/<int:pk>/<int:pk_offer>", views.offer_update, name="offer-update"),
    path("offer/delete/<int:pk>/<int:pk_offer>", views.offer_delete, name="offer-delete"),
    path("offer/update/visible/<int:pk>/<int:pk_offer>", views.offer_visible_update, name="offer-update-visible"),
    path("offer/update/photos/<int:pk>/<int:pk_offer>", views.OfferPhotosUpdate.as_view(), name="offer-update-photos"),
    path("offer/review/add/<int:pk>/<int:pk_offer>", views.offer_add_review, name="offer-add-review"),
    path("offer/review/<int:pk_offer>", views.offer_review_list, name="offer-review-list"),
    path("offer/detail/<int:pk>", views.OfferDetail.as_view(), name="offer-detail"),

    path("request/list/<int:pk>", views.request_list, name="request-list"),
    path("request/add/<int:pk>", views.RequestAdd.as_view(), name="request-add"),
    path("request/update/<int:pk>/<int:pk_request>", views.request_update, name="request-update"),
    path("request/delete/<int:pk>/<int:pk_request>", views.request_delete, name="request-delete"),
    path("request/detail/<int:pk>", views.RequestDetail.as_view(), name="request-detail"),
    path("request/add/offer/<int:pk_request>", views.offer_to_request, name="offer-to-request"),
    path("request/list/offers/<int:pk_request>", views.offers_for_request_list, name="offers-for-request-list"),

    path("offer/buy/<int:pk>/<int:pk_offer>", views.offer_buy, name="offer-buy"),
    path("offer/bought/list/<int:pk>", views.offers_bought_list, name="offers-bought-list"),

    path("offer/search", views.offer_search, name="offer-search"),

    path("seller/search", views.seller_search, name="seller-search"),

    path("orders/<int:pk>", views.orders, name="orders"),

]

ProgettoArduAlessio/user_management/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from django.contrib.auth import views as auth_views

from ProgettoArduAlessio import settings
from user_management import views

app_name = "user_management"

urlpatterns = [
    path("home/<int:pk>", views.user_detail, name="home"),

    path("register", views.UserCreateView.as_view(), name="register"),
    path("login", auth_views.LoginView.as_view(), name="login"),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),

    path('check_username_unique', views.check_username_is_unique, name='check-username-unique'),
    path('check_email_unique', views.check_email_is_unique, name='check-email-unique'),
]

ProgettoArduAlessio/Base/models.py
from django.db import models

# Create your models here.

ProgettoArduAlessio/Base/views.py
from django.shortcuts import render

# Create your views here.
from posts.models import Offer, Request, BoughtOffers, Review, Category
from django_pandas.io import read_frame
from scipy.stats import beta
from django.core.exceptions import ObjectDoesNotExist


def home(request):
    recommended_offers = None
    if request.user.is_authenticated:
        bought_offers_queryset = BoughtOffers.objects.filter(user=request.user.pk).distinct().values_list('offer',
                                                                                                          flat=True)
        bought_offers = Offer.objects.filter(pk__in=list(bought_offers_queryset))
        list_bought = [offer for offer in bought_offers]
        categories_bought = list(set([offer.category for offer in list_bought]))
        categories_rank_for_user = {}
        review_count_perstar_percategory = {}

        for cat in categories_bought:
            for offer in list_bought:
                if offer.category.pk == cat.pk:
                    try:
                        review = Review.objects.get(user=request.user.pk, offer=offer.pk)
                    except ObjectDoesNotExist:
                        review = None

                    if review is not None:
                        if cat.pk not in review_count_perstar_percategory:
                            review_count_perstar_percategory[cat.pk] = dict()
                        if review.stars not in review_count_perstar_percategory[cat.pk]:
                            review_count_perstar_percategory[cat.pk][review.stars] = 0

                        review_count_perstar_percategory[cat.pk][review.stars] += 1

        for k, v in review_count_perstar_percategory.items():
            q = 0
            up = 1
            down = 1
            for i in range(1, 6):
                if i not in v:
                    q = 0
                else:
                    q = v[i]
                if q != 0:
                    up += q * (i / 5)
                    down += q * (1 - (i / 5))
            categories_rank_for_user[k] = beta.ppf(0.05, up, down)

        favorite_categories = sorted(list(categories_rank_for_user.items()), key=lambda t: t[1])[:2]

        recommended_offers = []
        for t in favorite_categories:
            cat_pk = t[0]
            recommended_offers.extend(sorted(
                Category.objects.get(pk=cat_pk).offers.exclude(user=request.user.pk).exclude(
                    pk__in=bought_offers_queryset), key=lambda t: t.rank, reverse=True))
    if recommended_offers:
        recommended_offers = [offer for offer in recommended_offers if offer.deleted_but_visible_home == False]
    context = {
        "offers_recently_added": Offer.objects.all().filter(deleted_but_visible_home=False).order_by("-date")[:10],
        "requests_recently_added": Request.objects.order_by("-date")[:10],
        "recommended_offers": recommended_offers,
    }

    return render(request, "home.html", context)

ProgettoArduAlessio/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static "css/image_slider.css" %}"/>
    {% comment %}<link rel="stylesheet" type="text/css" href="{% static "css/general.css" %}"/> {% endcomment %}
      <title>{% block title %} {% endblock %}</title>

  </head>
  <body>

    {% include "navbar.html" %}

    {% block central_content %}

    {% endblock %}

    <div class="container-fluid">
          <div class="row d-flex justify-content-center" >
            <div class="col-md-9">
                <div class="mt-5">
                    {% block centered_central_content %}
                    {% endblock %}
                </div>
            </div>
         </div>
    </div>




    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% block javascript %}
    {% endblock %}
  </body>
</html>

ProgettoArduAlessio/templates/form.html
{% load crispy_forms_tags %}

<form method="post" {% if photo %} enctype='multipart/form-data' {% endif %} >{% csrf_token %}
    {{ form|crispy }}

    {% if view_type == "context_url" %}
    <a href="{{ url }}" class = "btn btn-danger">Cancel</a>
    {% else %}
    <input class = "btn btn-danger" type="submit" name="cancel" value="Cancel" />
    {% endif %}

    <input class = "btn btn-success" type="submit" value="{{ value }}"/>
</form>

ProgettoArduAlessio/templates/home.html
{% extends "base.html" %}
{% block central_content %}

    <div class="container-fluid">
        <h4 class="pt-2">Offers: recently added</h4>
        <div class="row d-flex flex-nowrap">
            {% for offer in offers_recently_added %}
                <div class="col col-md-auto  d-flex">
                    {% include "posts/offer/card_main_home.html" with offer=offer userObject=None main_home=True incremental_number=1%}
                </div>
            {% endfor %}
        </div>

        <h4 class="pt-2">Requests: recently added</h4>

        <div class="row d-flex flex-nowrap mb-3">
        {% for request in requests_recently_added %}
            <div class="col col-md-auto  d-flex">
                {% include "posts/request/card_main_home.html" with request=request userObject=None main_home=True%}
            </div>
        {% endfor %}
        </div>
        {% if user.is_authenticated %}
            {% if recommended_offers %}
                <h4 class="pt-2">Recommended offers</h4>

                    <div class="row d-flex flex-nowrap mb-3">
                    {% for offer in recommended_offers %}
                        <div class="col col-md-auto  d-flex">
                            {% include "posts/offer/card_main_home.html" with offer=offer userObject=None main_home=True incremental_number=2%}
                        </div>
                    {% endfor %}
                </div>
                {% endif %}
        {% endif %}
    </div>

{% endblock %}

ProgettoArduAlessio/templates/navbar.html
   <div class="d-flex mb-5 pb-1">
    <nav class="navbar navbar-expand-lg navbar-light bg-light  " style="position: fixed;top: 0px; width: 100%; z-index:99;">

      <a class="navbar-brand" href={% url "home" %}>Main Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse  " id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

          {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Profile
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url "user_management:home" user.pk %}">Homepage</a>
                  <a class="dropdown-item" href="{% url "posts:request-list" user.pk %}">Manage Requests</a>
                  <a class="dropdown-item" href="{% url "posts:offers-bought-list" user.pk %}">Bought Offers</a>
                  <a class="dropdown-item" href="{% url "posts:orders" user.pk %}">Orders</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url "user_management:logout" %}">Logout</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Messages
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{% url "integrated_messaging:inbox" %}">Chat</a>
                  </div>
              </li>
          {% endif %}
            {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href={% url "user_management:login" %} tabindex="-1">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href={% url "user_management:register" %}>Register</a>
                </li>
            {% endif %}

        </ul>

          <a href="{% url "posts:offer-search" %}" class="btn btn-outline-success my-2 my-sm-0" >Search Offers</a>
          <a href="{% url "posts:seller-search" %}" class="btn btn-outline-info ml-1 my-2 my-sm-0" >Best Sellers</a>

      </div>

    </nav>


</div>