ProgettoArduAlessio/ProgettoArduAlessio/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Base import views
from ProgettoArduAlessio import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('user_management/', include('user_management.urls')),
    path('user_profile/', include('user_profile.urls')),
    path('posts/', include('posts.urls')),
    path('integrated_messaging/', include('integrated_messaging.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProgettoArduAlessio/posts/urls.py
from django.urls import path
from posts import views

app_name = "posts"

urlpatterns = [
    path("offer/add/<int:pk>", views.OfferAdd.as_view(), name="offer-add"),
    path("offer/update/<int:pk>/<int:pk_offer>", views.offer_update, name="offer-update"),
    path("offer/delete/<int:pk>/<int:pk_offer>", views.offer_delete, name="offer-delete"),
    path("offer/update/visible/<int:pk>/<int:pk_offer>", views.offer_visible_update, name="offer-update-visible"),
    path("offer/update/photos/<int:pk>/<int:pk_offer>", views.OfferPhotosUpdate.as_view(), name="offer-update-photos"),
    path("offer/review/add/<int:pk>/<int:pk_offer>", views.offer_add_review, name="offer-add-review"),
    path("offer/review/<int:pk_offer>", views.offer_review_list, name="offer-review-list"),
    path("offer/detail/<int:pk>", views.OfferDetail.as_view(), name="offer-detail"),

    path("request/list/<int:pk>", views.request_list, name="request-list"),
    path("request/add/<int:pk>", views.RequestAdd.as_view(), name="request-add"),
    path("request/update/<int:pk>/<int:pk_request>", views.request_update, name="request-update"),
    path("request/delete/<int:pk>/<int:pk_request>", views.request_delete, name="request-delete"),
    path("request/detail/<int:pk>", views.RequestDetail.as_view(), name="request-detail"),
    path("request/add/offer/<int:pk_request>", views.offer_to_request, name="offer-to-request"),
    path("request/list/offers/<int:pk_request>", views.offers_for_request_list, name="offers-for-request-list"),

    path("offer/buy/<int:pk>/<int:pk_offer>", views.offer_buy, name="offer-buy"),
    path("offer/bought/list/<int:pk>", views.offers_bought_list, name="offers-bought-list"),

    path("offer/search", views.offer_search, name="offer-search"),

    path("seller/search", views.seller_search, name="seller-search"),

    path("orders/<int:pk>", views.orders, name="orders"),

]

ProgettoArduAlessio/user_management/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from django.contrib.auth import views as auth_views

from ProgettoArduAlessio import settings
from user_management import views

app_name = "user_management"

urlpatterns = [
    path("home/<int:pk>", views.user_detail, name="home"),

    path("register", views.UserCreateView.as_view(), name="register"),
    path("login", auth_views.LoginView.as_view(), name="login"),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),

    path('check_username_unique', views.check_username_is_unique, name='check-username-unique'),
    path('check_email_unique', views.check_email_is_unique, name='check-email-unique'),
]

ProgettoArduAlessio/posts/forms.py
from decimal import Decimal

from django import forms
from django.forms import NumberInput

from posts.models import Offer, Review, Post, Request, Category


class OfferAddForm(forms.ModelForm):
    image_field = forms.ImageField(label="Images", widget=forms.ClearableFileInput(attrs={'multiple': True}))

    class Meta:
        model = Offer
        fields = ("title", "description", "category", "price", "currency",)


class OfferPhotosUpdateForm(forms.Form):
    image_field = forms.ImageField(label="Images", widget=forms.ClearableFileInput(attrs={'multiple': True}))


class OfferUpdateForm(forms.ModelForm):
    class Meta:
        model = Offer
        fields = ("title", "description", "category", "price", "currency",)


class RequestUpdateForm(forms.ModelForm):
    class Meta:
        model = Request
        fields = ("title", "description", "category", "price", "currency",)


class DeleteConfirmationForm(forms.Form):
    deleted_but_visible_home = forms.BooleanField(
        label="Check this if you want the offer to be not public but visible in your homepage",
        required=False
    )


class OfferAddReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ("stars", "comment", )


class RequestAddForm(forms.ModelForm):

    class Meta:
        model = Request
        fields = ("title", "description", "category", "price", "currency",)


class OfferSearchForm(forms.Form):
    category = forms.ModelChoiceField(Category.objects, required=False)
    best_reviews = forms.BooleanField(
        label="Order by best reviews",
        required=False)

    price_bottom_threshold = forms.DecimalField(decimal_places=2, max_digits=12, min_value=Decimal('0.01'), required=False, )
    price_top_threshold = forms.DecimalField(decimal_places=2, max_digits=12, min_value=Decimal('0.01'), required=False, )


class SellerSearchForm(forms.Form):
    count = forms.IntegerField(widget=NumberInput(attrs={'type': 'range', 'step': '2'}))
    pass

ProgettoArduAlessio/posts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView

from django.views.generic.edit import FormView, UpdateView

from user_management.models import MyUser
from .forms import OfferAddForm, OfferUpdateForm, DeleteConfirmationForm, OfferAddReviewForm, \
    OfferPhotosUpdateForm, RequestAddForm, RequestUpdateForm, OfferSearchForm, SellerSearchForm
from .models import Offer, OfferImage, Review, Request, OfferRequest, BoughtOffers
from .templatetags.bought_count import bought_count


class OfferAdd(LoginRequiredMixin, FormView):
    form_class = OfferAddForm
    template_name = 'posts/offer/add.html'
    success_url = reverse_lazy("home")

    def get_success_url(self):
        pk = self.kwargs.get('pk', False)
        return reverse_lazy('user_management:home', kwargs={'pk': pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        pk = self.kwargs.get('pk', False)
        context['url'] = reverse_lazy("user_management:home", args=(pk,))

        return context

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        user_pk = kwargs.get('pk', False)
        user = MyUser.objects.get(pk=user_pk)
        files = request.FILES.getlist('image_field')
        if form.is_valid():
            offer = Offer(
                user=user,
                title=form.cleaned_data['title'],
                description=form.cleaned_data['description'],
                price=form.cleaned_data['price'],
                currency=form.cleaned_data['currency'],
                category=form.cleaned_data['category'],
            )
            offer.save()
            for f in files:
                offer_image = OfferImage(offer=offer, photo=f)
                offer_image.save()

            return self.form_valid(form)
        else:
            return self.form_invalid(form)


@login_required
def offer_update(request, **kwargs):
    pk = kwargs.get("pk", False)
    pk_offer = kwargs.get("pk_offer", False)
    userObject = MyUser.objects.get(pk=pk)

    offer = userObject.offers.get(pk=pk_offer)

    if request.method == 'POST':
        form = OfferUpdateForm(request.POST, instance=offer)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy("user_management:home", args=(pk,)))
    else:
        return render(request, "posts/offer/update.html",
                      {"form": OfferUpdateForm(instance=offer),
                       "url": reverse_lazy("user_management:home", args=(pk,))})


@login_required
def offer_delete(request, **kwargs):
    pk = kwargs.get("pk", False)
    if request.method == 'POST':
        form = DeleteConfirmationForm(request.POST)
        if form.is_valid():
            pk_offer = kwargs.get("pk_offer", False)
            userObject = MyUser.objects.get(pk=pk)
            offer = userObject.offers.get(pk=pk_offer)
            if form.cleaned_data['deleted_but_visible_home'] is True:
                offer.deleted_but_visible_home = True
                offer.save()
            else:
                for image in offer.images.all():
                    image.photo.delete()
                    image.delete()
                userObject.offers.remove(offer)
                offer.delete()
            return redirect(reverse_lazy("user_management:home", args=(pk,)))
    else:
        return render(request, "posts/offer/delete.html",
                      {"form": DeleteConfirmationForm, "url": reverse_lazy("user_management:home", args=(pk,))})


@login_required
def offer_visible_update(request, **kwargs):
    pk = kwargs.get("pk", False)
    pk_offer = kwargs.get("pk_offer", False)
    userObject = MyUser.objects.get(pk=pk)
    offer = userObject.offers.get(pk=pk_offer)
    offer.deleted_but_visible_home = False
    offer.save()

    return redirect(reverse_lazy("user_management:home", args=(pk,)))


@login_required
def offer_add_review(request, pk="", pk_offer=""):
    user = MyUser.objects.get(pk=pk)  # user that wants to review
    offer = Offer.objects.get(pk=pk_offer)

    if request.method == 'POST':
        form = OfferAddReviewForm(request.POST)
        if form.is_valid():
            review = Review(
                user=user,
                offer=offer,
                stars=form.cleaned_data['stars'],
                comment=form.cleaned_data['comment'],
            )
            review.save()

            return redirect(reverse_lazy("user_management:home", args=(pk,), ))
    else:
        error_not_paid = False
        error_review_yourself = False

        if bought_count(user=user, offer=offer) == 0:
            error_not_paid = True

        # i can't review my own offers
        if offer.user == user:
            error_review_yourself = True

        context = {"error_review_yourself": error_review_yourself,
                   "error_not_paid": error_not_paid,
                   "form": OfferAddReviewForm,
                   "url": reverse_lazy("user_management:home", args=(pk,))
                   }

        return render(request, "posts/review/add.html", context)


class OfferList(ListView):
    model = Offer
    template_name = "posts/homepage_offer_list.html"

    ordering = ['date']


class OfferDetail(DetailView):
    model = Offer
    template_name = "posts/offer/detail.html"


class RequestDetail(DetailView):
    model = Request
    template_name = "posts/request/detail.html"


def offer_review_list(request, pk_offer):
    review_list = Offer.objects.get(pk=pk_offer).reviews.order_by("-stars")
    review_count = review_list.count()
    return render(request, "posts/review/offer_review_list.html", {"review_list": review_list, "review_count": review_count})


class OfferPhotosUpdate(LoginRequiredMixin, FormView):
    template_name = "posts/offer/update_photos.html"
    form_class = OfferPhotosUpdateForm

    def get_success_url(self):
        pk = self.kwargs.get('pk', False)
        return reverse_lazy('user_management:home', kwargs={'pk': pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk', False)
        context['url'] = reverse_lazy("user_management:home", args=(pk,))
        return context

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        user_pk = kwargs.get('pk', False)
        offer_pk = kwargs.get('pk_offer', False)
        user = MyUser.objects.get(pk=user_pk)
        offer = Offer.objects.get(pk=offer_pk)
        files = request.FILES.getlist('image_field')
        if form.is_valid():
            for image in offer.images.all():
                image.photo.delete()
                image.delete()

            for f in files:
                offer_image = OfferImage(offer=offer, photo=f)
                offer_image.save()

            return self.form_valid(form)
        else:
            return self.form_invalid(form)

@login_required
def request_list(request, **kwargs):
    pk = kwargs.get("pk", False)
    userObject = MyUser.objects.get(pk=pk)
    requests = userObject.requests.all()

    context = {
        "userObject": userObject,
        "requests": requests,
    }
    return render(request, "posts/request/list.html", context)


class RequestAdd(LoginRequiredMixin, FormView):
    form_class = RequestAddForm
    template_name = 'posts/request/add.html'

    def get_success_url(self):
        pk = self.kwargs.get('pk', False)
        return reverse_lazy('posts:request-list', kwargs={'pk': pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk', False)
        context['url'] = reverse_lazy("posts:request-list", args=(pk,))

        return context

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        user_pk = kwargs.get('pk', False)
        user = MyUser.objects.get(pk=user_pk)
        if form.is_valid():
            user_request = Request(
                user=user,
                title=form.cleaned_data['title'],
                description=form.cleaned_data['description'],
                price=form.cleaned_data['price'],
                currency=form.cleaned_data['currency'],
                category=form.cleaned_data['category'],
            )
            user_request.save()

            return self.form_valid(form)
        else:
            return self.form_invalid(form)


@login_required
def request_update(request, **kwargs):
    pk = kwargs.get("pk", False)
    pk_request = kwargs.get("pk_request", False)
    userObject = MyUser.objects.get(pk=pk)

    user_request = userObject.requests.get(pk=pk_request)

    if request.method == 'POST':
        form = RequestUpdateForm(request.POST, instance=user_request)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy("posts:request-list", args=(pk,)))
    else:
        return render(request, "posts/request/update.html",
                      {"form": RequestUpdateForm(instance=user_request),
                       "url": reverse_lazy("posts:request-list", args=(pk,))})


@login_required
def request_delete(request, **kwargs):
    pk = kwargs.get("pk", False)
    pk_request = kwargs.get("pk_request", False)
    userObject = MyUser.objects.get(pk=pk)
    user_request = userObject.requests.get(pk=pk_request)
    if request.method == 'POST':
        userObject.requests.remove(user_request)
        user_request.delete()
        return redirect(reverse_lazy("posts:request-list", args=(pk,)))
    else:
        return render(request, "posts/request/delete.html",

ProgettoArduAlessio/posts/templates/posts/offer/add.html
{%  extends "user_profile/base.html" %}

{% block title %}
Add Offer
{% endblock %}
{% block central_content %}

    {% if view.kwargs.pk == user.pk %}

    {% include "form.html" with photo=True view_type="context_url" value="Add" %}

    {% else %}

    <div class="alert alert-warning" role="alert">
      You are not authorized
    </div>

    {% endif %}

{% endblock %}

ProgettoArduAlessio/posts/templates/posts/offer/bought_offers_list.html
{% extends "base.html" %}
{% block central_content %}

    <div class="container-fluid ">
        <h4 class="pt-2">Bought Offers</h4>
        {% if bought_offers %}
            <div class="row d-flex" >
                {% for offer in bought_offers %}
                    <div class="col-2 d-flex  "> {% comment %}d-flex align-items-stretch  flex-row flex-nowrap{% endcomment %}
                        {% include "posts/offer/card_main_home.html" with offer=offer userObject=None main_home=True%}
                    </div>
                {% endfor %}
            </div>
        {% else %}
            No Bought Offers Found
        {% endif %}
    </div>

{% endblock %}

ProgettoArduAlessio/posts/templates/posts/offer/buy.html
{%  extends "user_profile/base.html" %}

{% block central_content %}

    <h1>Do You Want to Buy Offer <b>{{ offer.title }}</b>?</h1>
    <form method="post">{% csrf_token %}
        <input class="btn btn-danger"type=button value="Cancel" onClick="javascript:history.go(-1);">
        <input class = "btn btn-success" type="submit" value="Buy"/>
    </form>


{% endblock %}

ProgettoArduAlessio/posts/templates/posts/offer/card.html
{% load static %}
{% load bought_count %}
{% load has_reviewed %}

    <div class="card  {% if offer.deleted_but_visible_home %} bg-secondary text-white {% endif %}text-center mt-3 "  >

    {% if offer.deleted_but_visible_home %}
        <div class="card-header">
            <strong>Deleted</strong>
        </div>
        {% if user.is_authenticated and userObject.pk == user.pk %}
            <a href="{% url "posts:offer-update-visible" userObject.pk offer.pk %}" class="btn btn-secondary">Publish again</a>
        {% endif %}
    {% endif %}

    {% if detail %}
        <div class="card-header">
            {% if offer.user.photo and offer.user.photo.name != "False"%}
                <img src="{{ offer.user.photo.url}}"  style="height: 1.55em" alt="...">
            {% else %}
                <img src="{% static "img/default-non-user-no-photo.jpg" %}"  style="height: 1.55em" alt="...">
            {% endif %}
            <a href="{% url "user_management:home" offer.user.pk %}"><strong>{{ offer.user }}</strong></a>
        </div>
    {% endif %}

    <div class="card-body " >
        <h3 class="card-title">{{ offer.title }} </h3>

        <div id="carouselExampleIndicators{{ offer.pk }}" class="carousel slide" data-ride="carousel" data-interval="false">
          <div class="carousel-inner">

              {% for image in offer.images.all %}
                  {% if forloop.counter == 1 %}
                    <div class="carousel-item active">

                        <div class="embed-responsive embed-responsive-16by9">
                            {% if user.is_authenticated and userObject.pk == user.pk %}
                                <a href="{% url "posts:offer-update-photos" userObject.pk offer.pk %}" data-toggle="tooltip" data-placement="bottom" title="Change photos"> <img src="{{ image.photo.url}}" class="card-img-top embed-responsive-item " alt="..."></a>
                            {% else %}
                                <img src="{{ image.photo.url}}" class="card-img-top embed-responsive-item" alt="...">
                            {% endif %}
                         </div>
                    </div>
                  {% else %}

                    <div class="carousel-item">
                      <div class="embed-responsive embed-responsive-16by9">
                            {% if user.is_authenticated and userObject.pk == user.pk %}
                                <a href="{% url "posts:offer-update-photos" userObject.pk offer.pk %}" data-toggle="tooltip" data-placement="bottom" title="Change photos"> <img src="{{ image.photo.url}}" class="card-img-top embed-responsive-item " alt="..."></a>
                            {% else %}
                                <img src="{{ image.photo.url}}" class="card-img-top embed-responsive-item" alt="...">
                            {% endif %}
                         </div>
                    </div>
                  {% endif %}
            {% endfor %}

          </div>
          {% if offer.images.all|length > 1 %}
              <a class="carousel-control-prev" href="#carouselExampleIndicators{{ offer.pk }}" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleIndicators{{ offer.pk }}" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
        {% endif %}
        </div>

        <p class="card-text border-top">
            <p><strong>Description</strong></p>
            {% if detail == True or user_home == True %}
                {{ offer.description }}
            {% else %}
                {% if offer.description|length < 70 %}
                    {{ offer.description }}
                {% else %}
                    {{ offer.description|slice:":70" }}...
                {% endif %}
             {% endif %}
            <div class="d-flex justify-content-between border-top mt-3 pt-3">
                <p class="font-weight-light">Category</p>
                <p class="font-weight-bold">{{ offer.category }}</p>
            </div>
            <div class="d-flex justify-content-between border-top mt-3 pt-3">
                <p class="font-weight-light">Price</p>
                <p class="font-weight-bold">{{ offer.currency }}{{ offer.price }}</p>
            </div>

            <div class="d-flex justify-content-between border-top mt-3 pt-3">
                <p class="font-weight-light">Mean stars</p>
            {% comment %}
            {% url posts:offer_review_list offer.pk %}
            {% endcomment %}
            <p class="font-weight-bold">
                {% if offer.mean_stars_review == None %}
                    No reviews
                {% else %}
                    <a href="{% url 'posts:offer-review-list' offer.pk %}">{{ offer.mean_stars_review|floatformat:1 }}({{ offer.review_count }})</a>
                {% endif %}
            </p>

            </div>
             <div class="d-flex justify-content-between">
                 <p></p>
                <p class="font-weight-light">{{ offer.date }}</p>
            </div>
            {% comment %}{{ offer.rank}}{% endcomment %}
            {% if user.is_authenticated and userObject.pk == user.pk %}
                <a href="{% url "posts:offer-update" userObject.pk offer.pk %}" class="btn btn-success">Edit</a>
                <a href="{% url "posts:offer-delete" userObject.pk offer.pk %}" class="btn btn-danger">Delete</a>
            {% endif %}
            {% if detail %}
                <input class="btn btn-info"type=button value="Previous Page" onClick="javascript:history.go(-1);">
            {% endif %}
            {% if user.is_authenticated %}
                {% if detail == True %}
                    <a href="{% url "posts:offer-buy" user.pk offer.pk %}" class="btn btn-success mb-1">Buy</a>

                {% endif %}
            {% endif %}
            {% if user.is_authenticated and userObject.pk != user.pk%}
                {% if detail != True and offer.deleted_but_visible_home == False %}
                    <a href="{% url "posts:offer-buy" user.pk offer.pk %}" class="btn btn-success mb-1">Buy</a>
                {% endif %}
                {% bought_count offer user as bought_count_var%}
                {% has_reviewed offer user as has_reviewed_var%}
                {% if bought_count_var > 0  %}
                    {% if not has_reviewed_var %}
                        <a href="{% url "posts:offer-add-review" user.pk offer.pk %}" class="btn btn-warning mb-1">Submit a Review</a>
                    {% else %}
                        <p class="text-info">Already reviewed</p>
                    {% endif %}
                {% endif %}
            {% endif %}

        </p>

    </div>

</div>

ProgettoArduAlessio/posts/templates/posts/offer/card_main_home.html
{% load static %}
{% load bought_count %}
{% load has_reviewed %}

<div class="card text-center mt-3" style="width: 16em;"  >
    <div class="card-header">
        {% if offer.user.photo and offer.user.photo.name != "False"%}
            <img src="{{ offer.user.photo.url}}"  style="height: 1.55em" alt="...">
        {% else %}
            <img src="{% static "img/default-non-user-no-photo.jpg" %}"  style="height: 1.55em" alt="...">
        {% endif %}
        <a href="{% url "user_management:home" offer.user.pk %}"><strong>{{ offer.user }}</strong></a>
    </div>
    <div class="card-body mb-0 pb-0" >
        <div id="carouselExampleIndicators{{ offer.pk }}{{ incremental_number }}" class="carousel slide" data-ride="carousel" data-interval="false">
          <div class="carousel-inner">
              {% for image in offer.images.all %}
                  {% if forloop.counter == 1 %}
                    <div class="carousel-item active">
                        <div class="embed-responsive embed-responsive-16by9">
                            <img src="{{ image.photo.url}}" class="card-img-top embed-responsive-item" alt="...">
                         </div>
                    </div>
                  {% else %}

                    <div class="carousel-item">
                      <div class="embed-responsive embed-responsive-16by9">
                          <img src="{{ image.photo.url}}" class="card-img-top embed-responsive-item" alt="...">
                         </div>
                    </div>
                  {% endif %}
            {% endfor %}

          </div>
          {% if offer.images.all|length > 1 %}
              <a class="carousel-control-prev" href="#carouselExampleIndicators{{ offer.pk }}{{ incremental_number }}" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleIndicators{{ offer.pk }}{{ incremental_number }}" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
        {% endif %}
        </div>
        <h3 class="card-title" style="font-size: medium">
            {% if offer.title|length < 50 %}
                    {{ offer.title }}
                {% else %}
                    {{  offer.title|slice:":50" }}...
                {% endif %}
        </h3>
        <p class="card-text border-top">
                <p class="font-weight-bold"  style="text-align: right;">{{ offer.currency }}{{ offer.price }}</p>
                <p class="font-weight-bold  " style="text-align: right;">
                {% if offer.mean_stars_review == None %}
                {% else %}
                    <a href="{% url 'posts:offer-review-list' offer.pk %}">
                        <img src="{% static "img/orange_star.png" %}"  style="height: 1.55em" alt="...">
                        {{ offer.mean_stars_review|floatformat:1 }}
                        ({{ offer.review_count }})
                    </a>
                {% endif %}
                </p>
        </p>
    </div>
    <footer class="pb-2 pt-2 mt-0 border-top">

        {% if user.is_authenticated and choose_offer != True and user.pk != offer.user.pk%}
            <a href="{% url "posts:offer-buy" user.pk offer.pk %}" class="btn btn-outline-success mb-1">Buy</a>
        {% endif %}

        <a href="{% url "posts:offer-detail" offer.pk %}" class="btn btn-outline-info mb-1">View</a>
        {% if choose_offer %}
             <form method="post">{% csrf_token %}
                <button class="btn btn-outline-success" type="submit" name="pk_offer" value={{ offer.pk }}>Offer</button>
            </form>
        {% endif %}

    {% if user.is_authenticated %}
        {% bought_count offer user as bought_count_var%}
        {% has_reviewed offer user as has_reviewed_var%}
        {% if bought_count_var > 0  %}
            {% if not has_reviewed_var %}
                <a href="{% url "posts:offer-add-review" user.pk offer.pk %}" class="btn btn-warning mb-1">Submit a Review</a>
            {% else %}
                <p class="text-info">Already reviewed</p>
            {% endif %}
        {% endif %}
    {% endif %}


    </footer>
</div>

ProgettoArduAlessio/posts/templates/posts/offer/delete.html
{%  extends "user_profile/base.html" %}

{% block title %}
Delete Offer
{% endblock %}
{% block central_content %}

    {% if request.resolver_match.kwargs.pk == user.pk %}

    {% include "form.html" with photo=True view_type="context_url" value="Delete" %}

    {% else %}

    <div class="alert alert-warning" role="alert">
      You are not authorized
    </div>

    {% endif %}

{% endblock %}

ProgettoArduAlessio/posts/templates/posts/offer/detail.html
{%  extends "base.html" %}
{% block centered_central_content %}
    {% include "posts/offer/card.html" with offer=object userObject=None detail=True main_home=False%}
{% endblock %}

ProgettoArduAlessio/posts/templates/posts/offer/search.html
{%  extends "user_profile/base.html" %}
{% load crispy_forms_tags %}
{% block central_content %}

    <h1>Search Offers</h1>
    <form method="post">{% csrf_token %}
        {{ form|crispy }}
        {% comment %}<a href="{{ url }}" class = "btn btn-danger">Cancel</a>{% endcomment %}
        <input class="btn btn-info"type=button value="Previous Page" onClick="javascript:history.go(-1);">
        <input class = "btn btn-success" type="submit" value="Search"/>
    </form>


{% endblock %}

ProgettoArduAlessio/posts/templates/posts/offer/search_results.html
{% extends "base.html" %}
{% block central_content %}

    <div class="container-fluid ">
        <h4 class="pt-2">Offers</h4>
        {% if offers %}
            <div class="row d-flex " >
                {% for offer in offers %}
                    <div class="col-2 d-flex  "> {% comment %}d-flex align-items-stretch  flex-row flex-nowrap{% endcomment %}
                        {% include "posts/offer/card_main_home.html" with offer=offer userObject=None main_home=True%}
                    </div>
                {% endfor %}
            </div>
        {% else %}
            No Offers Found
        {% endif %}
    </div>

{% endblock %}

ProgettoArduAlessio/posts/templates/posts/offer/update.html
{%  extends "user_profile/base.html" %}

{% block title %}
Update Offer
{% endblock %}
{% block central_content %}

    {% if request.resolver_match.kwargs.pk == user.pk %}

    {% include "form.html" with photo=True view_type="context_url" value="Update" %}

    {% else %}

    <div class="alert alert-warning" role="alert">
      You are not authorized
    </div>

    {% endif %}

{% endblock %}

ProgettoArduAlessio/posts/templates/posts/offer/update_photos.html
{%  extends "user_profile/base.html" %}

{% block title %}
    Change photos
{% endblock %}

{% block central_content %}
    {% if view.kwargs.pk == user.pk %}

    {% include "form.html" with photo=True view_type="context_url" value="Update" %}

    {% else %}

    <div class="alert alert-warning" role="alert">
      You are not authorized
    </div>

    {% endif %}
{% endblock %}